[package]
name = "entity"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish = false
description = "Entity for database models"

[dependencies]
sea-orm = { workspace = true }
serde = { workspace = true }
derive_more = { workspace = true, features = ["full"] }
