//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

use crate::components::deployment::model::DeploymentStatus;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "deployment")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub agent_id: i32,
  pub site_id: String,
  pub version: Option<String>,
  pub commit_hash: Option<String>,
  pub commit_message: Option<String>,
  pub branch: Option<String>,
  pub upload_token: Option<String>,
  pub build_logs: Option<String>,
  pub deploy_preview_url: Option<String>,
  pub execution_time: DateTimeUtc,
  pub status: DeploymentStatus,
  pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
