//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

use crate::components::site::model::SiteType;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "site")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub site_id: String,
  pub user_id: String,
  pub server_id: Option<i32>,
  pub name: String,
  pub domain: Option<String>,
  pub storage_used: i32,
  pub status: String,
  pub r#type: SiteType,
  pub repo_url: Option<String>,
  pub created_at: DateTimeUtc,
  pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
