//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "deployment")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: u32,
  pub site_id: String,
  pub agent_id: u32,
  pub status: String,
  pub build_logs: Option<String>,
  pub deploy_preview_url: Option<String>,
  pub upload_token: Option<String>,
  pub execution_time: DateTimeUtc,
  pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
