//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::EnumIter;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: u32,
  #[sea_orm(unique)]
  pub user_id: String,
  pub nickname: String,
  pub password: String,
  pub email: String,
  pub r#type: String,
  pub status: String,
  pub is_email_verified: i8,
  pub is_phone_verified: i8,
  pub created_at: DateTimeUtc,
  pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
